# Pandas DataFrame.loc()

    df.loc() is mostly about the df.loc('row') but
    Colon-comma makes your d.loc(:, 'column') show.
    
So, the API for .loc() is mostly just this:

    df.loc[row-label, col-label]

So for the very common simple task of selecting columns by label, you need to know some special Pythonic magic: 

    df.loc[:, col-label]

This colon is Python short-hand for a slice from beginning to end... or in other words "all rows". This is the single most confusing part of the Pandas API, which becoming more and more important because the old ways of selecting rows are deprecated.

In [ ]:
import pandas as pd

pd.set_option('display.max_columns', 500)

def a1_notation(n):
    string = ""
    while n > 0:
        n, remainder = divmod(n - 1, 26)
        string = chr(65 + remainder) + string
    return string

# First we create a 30 x 30 DataFrame with both row and column labels.
alist = list(range(1, 31))
A1_list = [a1_notation(x) for x in alist]
A1_list_plus = ["%s-label" % a1_notation(x) for x in alist]
df = pd.DataFrame([alist for aline in alist], columns=A1_list, index=A1_list_plus)
df

In [ ]:
# Using a single row-label with .loc() returns a the row as a Pandas Series.
df.loc['A-label']

## Let's Talk about Rows

In [15]:
df_blah

          D  H   L   N  foo
A-label   4  8  12  14  NaN
B-label   4  8  12  14  NaN
C-label   4  8  12  14  NaN
D-label   4  8  12  14  NaN
E-label   4  8  12  14  NaN
F-label   4  8  12  14  NaN
G-label   4  8  12  14  NaN
H-label   4  8  12  14  NaN
I-label   4  8  12  14  NaN
J-label   4  8  12  14  NaN
K-label   4  8  12  14  NaN
L-label   4  8  12  14  NaN
M-label   4  8  12  14  NaN
N-label   4  8  12  14  NaN
O-label   4  8  12  14  NaN
P-label   4  8  12  14  NaN
Q-label   4  8  12  14  NaN
R-label   4  8  12  14  NaN
S-label   4  8  12  14  NaN
T-label   4  8  12  14  NaN
U-label   4  8  12  14  NaN
V-label   4  8  12  14  NaN
W-label   4  8  12  14  NaN
X-label   4  8  12  14  NaN
Y-label   4  8  12  14  NaN
Z-label   4  8  12  14  NaN
AA-label  4  8  12  14  NaN
AB-label  4  8  12  14  NaN
AC-label  4  8  12  14  NaN
AD-label  4  8  12  14  NaN

In [ ]:
# Using a row-label and a column-label in .loc() returns the contents of the cell.
df.loc['A-label', 'AD']

In [ ]:
# Using a single row-label INSIDE A LIST in .loc() returns that row as a DataFrame.
df.loc[['A-label']]

In [ ]:
# Using a list of row-labels in .loc() returns those specific rows as a DataFrame.
df.loc[['A-label', 'C-label', 'E-label', 'G-label', 'I-label']]

In [ ]:
# Using row-labels with slice notation in .loc() returns that range of rows as a DataFrame.
df.loc['A-label':'G-label']

In [ ]:
# Dropping the first row-label in slice notation in .loc() indicates starting at top of DataFrame.
df.loc[:'G-label']

In [ ]:
# Dropping the last row-label in slice notation in .loc() indicates ending at bottom of DataFrame.
df.loc['W-label':]

In [ ]:
# Dropping both row-labels in slice notation in .loc() selects the entire DataFrame (top to bottom).
df.loc[:]

In [ ]:
# As with iloc, there is a comma in the interface which seperates row arguments from column arguments.
df.loc[:, ]

## Let's Talk about Columns

In [ ]:
# If we use just a single label-name after the comma (like using an integer in iloc) we get a Pandas Series.
df.loc[:, 'A']

In [ ]:
# Putting a label-name in a list after the comma returns a DataFrame.
df.loc[:, ['A']]

In [ ]:
# This is how we perform the very common task of selecting specific columns by label.
df.loc[:, ['P', 'A', 'N', 'D', 'A', 'S']]

In [ ]:
# Label-based slice definitions can be used in place of lists.
df.loc[:, 'P':'U']

In [ ]:
# After the comma you can leave off the ending slice value for "to the end".
df.loc[:, 'P':]

In [ ]:
# After the comma you can leave off the beginning slice value for "from beginning".
df.loc[:, :'N']

## Rows & Columns

In [ ]:
# This is how we get the intersection of label-based slice definitions for rows and columns.
df.loc[:'N-label', :'N']

In [ ]:
# We can use lists of labels to define intersections. If each list has one item, we get a 1-cell DataFrame
df.loc[['N-label'], ['N']]

In [ ]:
# If you're going for a single value, there's not much sense in asking for a DataFrame to be returned.
df.loc['N-label', 'N']

In [ ]:
# We can use references (variable names) to make list-intersection requests more readable.
rows = ['P-label', 'A-label', 'N-label', 'D-label', 'A-label', 'S-label']
cols = ['P', 'A', 'N', 'D', 'A', 'S']
df.loc[rows, cols]

In [ ]:
# We can use list comprehension and the enumerate and modulus functions to list every other column. 
[(i, x)[1] for i, x in enumerate(list(df.columns)) if i%2]

In [ ]:
# This is how we select every other column by label name.
df.loc[:, [(i, x)[1] for i, x in enumerate(list(df.columns)) if i%2]]

In [ ]:
# We generate a warning and get a column full of NaN addressing nonexistant columns
df.loc[:,['foo', 'B', 'A', 'R']]

In [15]:
df_blah

          D  H   L   N  foo
A-label   4  8  12  14  NaN
B-label   4  8  12  14  NaN
C-label   4  8  12  14  NaN
D-label   4  8  12  14  NaN
E-label   4  8  12  14  NaN
F-label   4  8  12  14  NaN
G-label   4  8  12  14  NaN
H-label   4  8  12  14  NaN
I-label   4  8  12  14  NaN
J-label   4  8  12  14  NaN
K-label   4  8  12  14  NaN
L-label   4  8  12  14  NaN
M-label   4  8  12  14  NaN
N-label   4  8  12  14  NaN
O-label   4  8  12  14  NaN
P-label   4  8  12  14  NaN
Q-label   4  8  12  14  NaN
R-label   4  8  12  14  NaN
S-label   4  8  12  14  NaN
T-label   4  8  12  14  NaN
U-label   4  8  12  14  NaN
V-label   4  8  12  14  NaN
W-label   4  8  12  14  NaN
X-label   4  8  12  14  NaN
Y-label   4  8  12  14  NaN
Z-label   4  8  12  14  NaN
AA-label  4  8  12  14  NaN
AB-label  4  8  12  14  NaN
AC-label  4  8  12  14  NaN
AD-label  4  8  12  14  NaN